import { z } from 'zod';

const text = z.string().nullish();
const numeric = z.union([z.number(), z.string()]).nullish();
const flag = z.boolean().nullish();
const practice = z.looseObject({ Name: text, Business_Email__c: text, Business_Phone__c: text });
const provider = z.looseObject({
  Name: text,
  Email__c: text,
  Phone__c: text,
  Practice_Name__c: text,
  Practice_Name__r: practice.nullish(),
});
export const collectedSlaSchema = z.looseObject({
  Name: text,
  Statuss__c: text,
  LastModifiedDate: text,
  CreatedDate: text,
  Stage__c: text,
  Team__c: text,
  Reason_for_Delay__c: text,
  Reason_for_Delay_Notes__c: text,
  Reason_for_Delay_Notes_Last_Updated__c: text,
  Action_Item_Update__c: text,
  Action_Item__c: text,
  Provider_Action_Items__c: text,
  SLA_Days__c: numeric,
  Due__c: numeric,
  Due_Date_New__c: text,
});
/** Decode the fields consumed by this workflow; retain unconsumed Salesforce metadata verbatim. */
export const collectedOpportunitySchema = z.looseObject({
  Id: z.string(),
  Name: z.string(),
  StageName: text,
  LastModifiedDate: text,
  CreatedDate: text,
  CSM__c: text,
  Practice_Name__c: text,
  Phone__c: text,
  ContactId: text,
  Rendering_Provider__c: text,
  Rendering_Provider__r: provider.nullish(),
  IA_Rendering_Provider__c: text,
  IA_Rendering_Provider__r: provider.nullish(),
  TA_Rendering_Provider__c: text,
  TA_Rendering_Provider__r: provider.nullish(),
  Headstart_Practice__c: text,
  Headstart_Practice__r: practice.nullish(),
  Current_SLA__c: text,
  Current_SLA__r: collectedSlaSchema.nullish(),
  SLA_Status__c: text,
  SL_Due__c: numeric,
  On_Hold__c: flag,
  Has_IA_Approved__c: flag,
  Notes__c: text,
  Intake_Notes__c: text,
  Intake_Notes_Last_Updated__c: text,
  On_Hold_Reason__c: text,
  On_Hold_Notes__c: text,
  On_Hold_Notes_Last_Updated__c: text,
  On_Hold_Start_Date__c: text,
  On_Hold_End_Date__c: text,
  On_Hold_Follow_Up_Date__c: text,
  Current_Days_on_Hold__c: numeric,
  Total_Days_on_Hold__c: numeric,
  Last_On_Hold_Reason__c: text,
  Off_Hold_Reason__c: text,
  Current_Treatment_Plan_Status__c: text,
  Current_TP_Sent_for_Signatures__c: text,
  IC_Scheduled_For__c: text,
  IC_Scheduled_On__c: text,
  IC_Completed_Date__c: text,
  IC_Scheduling_Status__c: text,
  IA_Scheduled_For__c: text,
  IA_Scheduled_On__c: text,
  IA_Scheduled_Timestamp__c: text,
  IA_Completed_Date__c: text,
  IA_Scheduling_Status__c: text,
  Has_IA_Completed__c: flag,
  Intake_Packet_Status__c: text,
  Intake_Packet_Sent_Timestamp__c: text,
  Intake_Packet_Completed_Timestamp__c: text,
  Vineland_Status__c: text,
  Vineland_Sent_Timestamp__c: text,
  Vineland_Awaiting_Send_Timestamp__c: text,
  Vineland_Completed_Timestamp__c: text,
  Vineland_Filed_Timestamp__c: text,
  BASC_Status__c: text,
  BASC_Sent_Timestamp__c: text,
  BASC_Awaiting_Send_Timestamp__c: text,
  BASC_Completed_Timestamp__c: text,
  BASC_Filed_Timestamp__c: text,
  X97153_Scheduled_For__c: text,
  X53_Provider_Confirmed_First_Day_TS__c: text,
  First_day_of_Treatment__c: text,
  Est_First_Day_of_Treatment__c: text,
  Initial_Auth_Approval_Date__c: text,
  IA_Approval_Checked_Timestamp__c: text,
  Treatment_Auth_Approval_Date__c: text,
  TA_Approval_Checked_Timestamp__c: text,
  Active_RBT_Checked_At__c: text,
  SLA_Entry_Date__c: text,
  LastStageChangeDate: text,
  Current_Stage_Duration__c: numeric,
  SLA_Reason_for_Delay_Notes_Last_Updated__c: text,
  Close_Suggestion__c: text,
});
export type CollectedSla = z.infer<typeof collectedSlaSchema>;
export type CollectedOpportunity = z.infer<typeof collectedOpportunitySchema>;
